# Subject
- name: bug
  description: Something is broken
  color: e57373
- name: build
  description: Build or CI process
  color: dce775
- name: documentation
  description: Documentation changes
  color: dce775
- name: feature
  description: A new feature!
  color: 81c784
- name: performance
  description: An enhancement to or problem with performance
  color: 64b5f6
- name: security
  description: A security concern or vulnerability
  color: e57373
- name: upstream
  description: Caused by an upstream dependency
  color: f7ae7e

# Meta
- name: blocked
  description: ""
  color: e0e0e0
- name: duplicate
  description: ""
  color: e0e0e0

# Platforms
- name: linux
  description: Linux-specific issue
  color: a1887f
- name: macos
  description: macOS-specific issue
  color: a1887f
- name: windows
  description: Windows-specific issue
  color: a1887f
